Added functionality for `grades_persistent_tables
mitodl/edx2bigquery pull request #58
Opened 2017-08-22 21:03 UTC by lstmemery

I've added functionality creating and inserting data into `grades_persistent` and `grades_persistent_subsection.`

The command to create `grades_persistent` is:
`grades_persistent`

to create `grades_persistent_subsection`:
`--subsection grades_persistent`.

I've added the schemas. The descriptions were populated from [here](http://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/sql_schema.html).

The main function I created is `make_grading_policy_table.upload_grade_persistent_data.` I have tested it. I have also added the two versions of this function in `doall`. 

If you need me to do anything else, I'll happily oblige.

2017-08-22 22:52 UTC, ichuang commented
Thanks for the contribution!  The helpful comments are especially appreciated.

Some questions:

What's the role of the `edx2bigquery/make_grades _table.py` file?

Also, does it make sense to put the `upload_grades_persistent_data` function inside the `edx2bigquery/make_grading_policy_table.py` file, given that it is doing something separate from the `grading_policy` data?

2017-08-22 22:57 UTC, ichuang requested changes

2017-08-22 22:57 UTC, ichuang commented on edx2bigquery/main.py
> -    elif (args.command=='grading_policy'):
Why did you remove the `grading_policy` command?

2017-08-22 22:57 UTC, ichuang commented on edx2bigquery/main.py
> -        make_grading_policy(param, course_id, args)
Why remove the call to `make_grading_policy` in doall?

2017-08-23 16:46 UTC, lstmemery commented
I've re-added the `grading_policy` functionality (my mistakes!) and moved all the new functionality into `make_grades_persistent.py`.

2017-08-23 16:47 UTC, lstmemery commented on edx2bigquery/main.py
> -    elif (args.command=='grading_policy'):
Fixed!

2017-08-23 16:47 UTC, lstmemery commented on edx2bigquery/main.py
> -        make_grading_policy(param, course_id, args)
Fixed!

2017-08-23 17:26 UTC, ichuang commented on edx2bigquery/main.py
> +import edx2bigquery.make_grades_persistent
Is this import statement needed?

2017-08-23 17:54 UTC, lstmemery commented on edx2bigquery/main.py
> +import edx2bigquery.make_grades_persistent
Nope. It was an artifact of a refactoring.

2017-08-23 18:47 UTC, ichuang approved these changes

2017-08-23 18:51 UTC, merged

2017-08-23 18:52 UTC, ichuang commented
Thanks for the helpful contribution!

2017-08-24 13:08 UTC, SdotGlenn commented
Many thanks Matt for this!